import { StyleSheet } from 'react-native';
import { borderRadius, font, fontSize, fontWeight, spacing } from '../globalStyles';

export const createStyles = (colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  rulesCard: {
    marginTop: 50,
    width: 290,
    height: 242,
    backgroundColor: colors.secondary,
    borderWidth: 1,
    borderColor: colors.warning,
    borderRadius: borderRadius.xl,
    padding: spacing.lg,
    zIndex: 2,
  },
  rulesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  rulesTitle: {
    fontFamily: font.fontFamily,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.md,
    color: colors.fontColor,
  },
  alertIcon: {
    width: 25,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: borderRadius.lg,
    borderWidth: 2,
    borderColor: colors.warning,
  },
  alertIconText: {
    fontSize: fontSize.lg,
    color: colors.warning,
  },
  rulesText: {
    fontFamily: font.fontFamily,
    fontWeight: fontWeight.normal,
    fontSize: fontSize.md,
    lineHeight: 20,
    color: colors.fontColor,
    marginBottom: 15,
  },
  logoContainer: {
    marginTop: 25,
    marginBottom: 10,
    alignItems: 'center',
  },
  title: {
    width: 183,
    height: 30,
    fontFamily: font.fontFamily,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.md,
    lineHeight: 30,
    color: colors.fontColor,
    textAlign: 'center',
  },
  subtitle: {
    width: 290,
    height: 40,
    fontFamily: font.fontFamily,
    fontWeight: fontWeight.medium,
    fontSize: fontSize.md,
    lineHeight: 20,
    color: colors.fontColor,
    textAlign: 'center',
  },
  formContainer: {
    width: 290,
    height: 220,
    backgroundColor: colors.secondary,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.lg,
    paddingHorizontal: 36,
    justifyContent: 'space-around',
  },
  inputContainer: {
    width: 218,
    height: 40,
    alignSelf: 'center',
  },
  input: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.terciario,
    borderRadius: borderRadius.sm,
    paddingHorizontal: spacing.sm + 4,
    paddingVertical: spacing.sm + 4,
    fontFamily: font.fontFamily,
    fontWeight: fontWeight.normal,
    fontSize: fontSize.xs,
    color: colors.fontColor,
  },
  eyeIcon: {
    position: 'absolute',
    right: 13,
    top: 12.5,
    width: 15,
    height: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  eyeIconImage: {
    width: 15,
    height: 12,
  },
  button: {
    width: 218,
    height: 40,
    backgroundColor: colors.button,
    borderRadius: borderRadius.sm,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonText: {
    fontFamily: font.fontFamily,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.md,
    lineHeight: 20,
    color: colors.fontColor,
  },
});